name: Test

on: 
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: install
        run: npm ci
      - name: test
        run: npm test
      - uses: actions/upload-artifact@v4
        with:
          name: test-${{github.sha}}
          path: test
      - name: move to dir
        run: |
          cp -rf ./test/main.css ./main.css
          cp -rf ./test/cv/styles/mods/*.css ./mods/
      - name: Commit files
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./main.css
          git add ./mods/*
          git commit -m "Upload compiled"
          git push